import Head from 'next/head'
import Navbar from '@/components/navbar'
import Herosection from '@/components/Herosection'
import { useEffect, useState } from 'react'


export default function Home() {
  const [darkmode, setDarkmode] = useState(false)
useEffect(()=>{
  if(localStorage.getItem("darkmode") == undefined) {
    localStorage.setItem("darkmode","true")
  } 

setDarkmode(localStorage.getItem("darkmode")=="true")


},[])
  const toggleDark = () => {
    

     localStorage.setItem("darkmode",!darkmode)
     setDarkmode(!darkmode)
  }
  return (
    <div className={`${darkmode ? "dark":"light"}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
      </Head>
     <Navbar darkmode={darkmode}  toggleDark={toggleDark}/> 
     <Herosection /> 
    </div>
  )
}
